[project]
name = "part1-gridworld"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "beartype>=0.21.0",
    "numpy>=2.3.3",
    "pygame>=2.6.1",
]
